import 'package:flutter/material.dart';

class ManagerColors {
  static const Color secondaryColor = Color(0xff14B1AB);
  static const Color shadowCategory = Color(0x29000000);
  static const Color white = Colors.white;
  static const Color black = Colors.black;
  static const Color textColor = Color(0xFF072A33);
  static const Color textColorLight = Color(0xff525167);
  static const Color subTitleColor = Color(0xff839499);
  static const Color primaryColor = Color(0xffFFB300);
  static const Color borderSide = Color(0xff1A1919);
  static const Color buttonColorLight = Color(0xFFA7E4DC);
  static const Color buttonColorDarK = Color(0xFFA7E4DC);
  static const Color forgetTextColor = Color(0xff1CA0BF);
  static const Color paymentSelectorBorderSide = Color(0xff1CA0BF);
  static const Color greyLight = Color(0xFFD5D5D5);
  static const Color primaryColorDark = Color(0xFFB8C9CC);
  static const Color primaryColorLight = Color(0xFF000333);
  static const Color background = Color(0xFFF2F7F7);
  static const Color backgroundForm = Color(0xFFF8F8F8);
  static const Color grey = Colors.grey;
  static const Color red = Colors.red;
  static const Color blue = Colors.blue;
  static const Color backgroundCategory = Color(0xFEDD6800);
  static const Color backgroundCategories = Color(0xFFF1F1F1);
  static const Color selectedCategory = Color(0xFFFFC727);
  static const Color backgroundCourses = Color(0xffFFF3F3);
  static const Color backgroundResource = Color(0xffFFF3F3);
  static const Color textColorProfile = Color(0xFF403E39);
  static const Color textColorProfileInformation = Color(0xFF737373);
  static const Color activeSwitchColor = Color(0xff4CD964);
  static const Color textColorAppoint = Color(0xff928F8E);
  static const Color notVerifiedStatus = Color(0xffCACACA);
  static const Color verifiedStatus = Color(0xff30C165);
  static const Color cancelledStatus = Color(0xffF05353);
  static const Color searchColor = Color(0xffADADAD);
  static const Color descriptionColor = Color(0xff6A7F84);
  static const Color enabledBorderInputVerification = Color(0xFF1A1919);
  static const Color focusedBorderInputVerification = primaryColor;
  static const Color fillInputVerification = Color(0xffF0F0F0);
  static const Color transparent = Colors.transparent;
  static const Color iconColor = Colors.white;
  static const Color scaffoldBackgroundColor = Color(0xFFFBFBFE);
  static const Color shimmerFirstColor = Color(0xE0D7D9DA);
  static const Color shimmerSecondColor = Color(0xF5F5F5FF);
  static const Color orLoginTextColor = Color(0xFF1C1C1C);
  static const Color rememberMe = Color(0xFF1C1C1C);
  static const Color textFieldColor = Color(0xFFDBDBDB);
  static const Color textCheckBoxColor = Color(0xFF3D3D3D);
  static const Color textResourceColor = Color(0xFF111111);
  static const Color dividerColor = Color(0xFFE4E4E4);
  static const Color profileEmailColor = Color(0xFF9F9F9F);

}
