// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5aK6e_B9IeUSQW7gvB-PmZC58nCVs7Bw',
    appId: '1:791480986801:web:97eb9568f4c5628f1d4690',
    messagingSenderId: '791480986801',
    projectId: 'act-hub-43a6b',
    authDomain: 'act-hub-43a6b.firebaseapp.com',
    storageBucket: 'act-hub-43a6b.appspot.com',
    measurementId: 'G-G6JJQEXXCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD97EmRPxnIsi3LPYRoMmH-XSBbp-pXePg',
    appId: '1:791480986801:android:9a2fcaed2a3fb90f1d4690',
    messagingSenderId: '791480986801',
    projectId: 'act-hub-43a6b',
    storageBucket: 'act-hub-43a6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApCWvCyVS53hqBn19D7-4_uB-ij7GAY_8',
    appId: '1:791480986801:ios:66a12aeda8559fd91d4690',
    messagingSenderId: '791480986801',
    projectId: 'act-hub-43a6b',
    storageBucket: 'act-hub-43a6b.appspot.com',
    iosClientId: '791480986801-tjn9v50i0snt3gppngi1aoltu52upj49.apps.googleusercontent.com',
    iosBundleId: 'com.example.actHubMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApCWvCyVS53hqBn19D7-4_uB-ij7GAY_8',
    appId: '1:791480986801:ios:66a12aeda8559fd91d4690',
    messagingSenderId: '791480986801',
    projectId: 'act-hub-43a6b',
    storageBucket: 'act-hub-43a6b.appspot.com',
    iosClientId: '791480986801-tjn9v50i0snt3gppngi1aoltu52upj49.apps.googleusercontent.com',
    iosBundleId: 'com.example.actHubMobile',
  );
}
